CREATE DATABASE IF NOT EXISTS recordingsdb;
CREATE DATABASE IF NOT EXISTS usersdb;
GRANT ALL PRIVILEGES ON recordingsdb.* TO 'eduvibe'@'%';
GRANT ALL PRIVILEGES ON usersdb.* TO 'eduvibe'@'%';
FLUSH PRIVILEGES;